version: '3.8'
services:
  webapp:
    build: .
    environment:
      MONGODB_URL: mongodb://database:27017/time-trials
    ports:
      - "8080:8080"
    depends_on:
      - "database"

  database:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - time-trials-volume:/data/db

volumes:
  time-trials-volume:
