version: '3.8'
services:
  webservice:
    build: .
    environment:
      MONGODB_URI: mongodb://database:27017/time-trials
      NEW_TIME_TOPIC: new-time
      BOOTSTRAP_SERVERS: kafka:9092
      CONSUMER_GROUP: time-consumer-group
    ports:
      - "8080:8080"
    depends_on:
      - "database"

  database:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - time-trials-volume:/data/db

  zookeeper:
    restart: always
    image: docker.io/bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-volume:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    restart: always
    image: &kafka-image bitnami/kafka:latest
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - kafka-volume:/bitnami
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    depends_on:
      - zookeeper
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--bootstrap-server=localhost:9092", "--list" ]
      start_period: 10s
      interval: 10s

  init-kafka:
    image: *kafka-image
    working_dir: /opt/bitnami/kafka/bin
    entrypoint: /bin/bash -c
    depends_on:
      kafka:
        condition: service_healthy
    command: |
      "
      kafka-topics.sh --create --if-not-exists --topic new-time --replication-factor=1 --partitions=1 --bootstrap-server kafka:9092
      "

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: "8081"
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: host.docker.internal:9092
    depends_on:
      - kafka

volumes:
  time-trials-volume:
  kafka-volume:
  zookeeper-volume:
